### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by oliver-sey** [passivebot/rewards-bot#1]
Got this error while trying to run the bot for the first time
'''
[DAILY SET] Trying to complete the Daily Set...
Traceback (most recent call last):
  File "main.py", line 77, in displayCredentials
  File "main.py", line 506, in completeDailySet
  File "main.py", line 502, in getDashboardData
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
'''

**Comment by SnowmanKing** [comment]
Same error I am getting

**Comment by Testsr** [comment]
My fork  has  fixed this.
